--liquibase formatted sql

--changeset a.khaustov:1
create table user_exchange_info
(
    id            bigint primary key generated by default as identity,
    api_key       varchar(255),
    secret_key    varchar(255),
    exchange_id bigint not null,
    constraint fk_exchange_info_exchange_id
        foreign key (exchange_id)
            references exchange(id),
    user_info_id  bigint              not null,
    constraint fk_exchange_info_user_info_id
        foreign key (user_info_id)
            references user_info(id)
);




